### ISSUE TITLE
First feedback

### ISSUE THREAD

**Issue by pitschr** [StefanOltmann/smart-home-server#1]
Hi Stefan.

I figured out few issues, documenting here so you may improve your readme.md page:

===========
1)
Is there a `Dockerfile` file available? I see a `dockerignore` file. Perhaps forgot to commit it?

===========
2)
When downloading the file `smart-home-server-0.1-macos-runner` required command to execute is:
 `chmod +x smart-home-server-0.1-macos-runner` (make it executable)

A dialog appears:
<img width="446" alt="warning" src="https://user-images.githubusercontent.com/25742159/112028380-6393eb80-8b38-11eb-8c5b-62c8107bed8a.png">

1) Abbrechen / Cancel (button)
2) Sicherheit / Security (application)
3) Allgemein / General (tab)
4) Trotzdem Erlauben / Open Anyway (button)

===========
3)
Perhaps document where to store the `keystore.jks`. I tried to place it in same folder like the runner application.
```
2021-03-22 18:03:23,572 ERROR [io.qua.run.Application] (main) Failed to start application (with profile prod): java.io.IOException: Invalid keystore format
	at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:667)
	at sun.security.util.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:222)
	at java.security.KeyStore.load(KeyStore.java:1479)
 ... lines omitted ...
```

The startup with `*.jar` file was more successful for me. Tip: For first impression perhaps HTTP should be allowed? Printing annoying warning messages in log file should be motivate to enable HTTPS as soon as possible.

This might be helpful for others as start
```
curl -k -H "AUTH_CODE: $(cat auth_code.txt)" https://localhost:50000/devices/current-states
```

===========
4)
Link to download the runner should probably point to https://github.com/StefanOltmann/smart-home-server/releases/ rather than to the "Actions page".

===========
5)
Does it mean to use your project I have to setup `devices.json` first? Perhaps we can fetch the most information from KNXPROJ file already?
See: https://github.com/pitschr/knx-core/tree/main/src/main/java/li/pitschmann/knx/core/knxproj

To get the parsed file, try get it from KnxClient#getConfig()#getProject() . If you are missing some features, let me know it. And I'll figure out how to extract it from the KNXPROJ file.

Let me if something is unclear, I'm happy to provide further info 😅

**Comment by StefanOltmann** [comment]
Hi Christoph,

thank you a lot for your feedback.
I really appreciate it. :)

1) No, this is just for a Docker container to build the native binary in. It comes with Quarkus standard layout.
Quarkus is really nice and fast by the way, you should check it out.

===========

2) Yeah, you are right. In standard setup there has to be made an exception to the security rules.
Since it works with Linux and Windows out of the box the bug realting to the MacOS binary is not worth the trouble.
I built it for MacOS because Quarkus supports that, but it's not likely. I removed that artifact.

===========

3) & 4) I updated the documentation regarding to that. Very good points! Thank you.

===========

5) Yeah, the devices.json is neccessary.

I currently look into how to use the parsed data, but I don't think the information is enough.

Just having group addesses in ranges does not give me a way to group them together for the devices.
And even if it also requires specific naming of the ranges to use that as a device name.

Is there a way to include device and channel information here?
That may be useful to guess what belongs together.

**Comment by pitschr** [comment]
> I currently look into how to use the parsed data, but I don't think the information is enough.
> 
> Just having group addesses in ranges does not give me a way to group them together for the devices.
> And even if it also requires specific naming of the ranges to use that as a device name.
> 
> Is there a way to include device and channel information here?

For the group address, I am already providing the name and description too. See:
https://github.com/pitschr/knx-core/blob/main/src/main/java/li/pitschmann/knx/core/knxproj/XmlGroupAddress.java

_(FYI - Flags are not implemented yet, I just realized it now - has no effect at the moment, so I probably remove it for the next release version)_

====

I checked KNXPROJ file and we have some information which datatype (e.g. DPT1), there is no information what exactly the object belongs to; e.g. lamp, rm, alarm, power ... as the ETS seems doesn't really take care about it. 

About the device, there seems be an ability to figure out which type of actuator it is, it is a free-text, but no enumeration or something like that where we can rely on it. Maybe I oversee something.

In my case the lamp is defined as DPST-1-1 which stands for DPT1#SWITCH. The lamp status is based on DPST-1-11 which stands for DPT1#STATE. But it is not a good idea to rely on it, since DPT1 could be also another (wrongly-configured) sub type of DPT1. From KNX bus point of view it doesn't matter since all sub types of DPT1 shares the same byte structure.

Guessing that would be bigger topic in advanced parsing area which might be an interesting topic in future - e.g. when only read-flag is enabled and DPT1 then we can assume that it is a state communication object, for example. To achieve that almost files inside KNXPROJ zip file needs to be pre-parsed as the flags may be inherited from manufacturer hardware description file 🙈 

They way with `devices.json` is probably the straight-forward solution; as I see OpenHAB is doing same way.

p.s. The ETS 5 XML Project Format Description can be found here (requires login to my.knx.org): 
https://my.knx.org/en/downloads/special

Perhaps you see something how and if it might be helpful to gather the information you need. I may support you here. Until then I plan to spend my energy for knx-link (and knx-logic)

p.p.s. I saw that there is a KNX Web Services based on Calimero Project and seems already offering what you need. Check out it if that would help you.
